export enum burgerConstructorActions {
    GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST',
    GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS',
    GET_INGREDIENTS_ERROR = 'GET_INGREDIENTS_ERROR',
    ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR',
    ADD_BUN_TO_CONSTRUCTOR = 'ADD_BUN_TO_CONSTRUCTOR',
    REMOVE_INGREDIENT_FROM_CONSTRUCTOR = 'REMOVE_INGREDIENT_FROM_CONSTRUCTOR',
    CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR',
    CHANGE_INGREDIENTS_ORDER = 'CHANGE_INGREDIENTS_ORDER',
    SEND_ORDER_REQUEST = 'SEND_ORDER_REQUEST',
    SEND_ORDER_SUCCESS = 'SEND_ORDER_SUCCESS',
    SEND_ORDER_ERROR = 'SEND_ORDER_ERROR',
}
